

<!--<form action="/" method="post">-->
<!--    <div class="form-group">-->
<!--        <label for="exampleInputText">Username</label>-->
<!--        <input type="text" name="name" value="" class="form-control" id="exampleInputText" placeholder="Username" required/>-->
<!--    </div>-->
<!--    <div class="form-group">-->
<!--        <label for="exampleInputEmail1">Email address</label>-->
<!--        <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" required/>-->
<!--        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
<!--    </div>-->
<!--    <div class="input-group">-->
<!--        <div class="input-group-prepend">-->
<!--            <span class="input-group-text">Enter message:</span>-->
<!--        </div>-->
<!--        <textarea name="desc" class="form-control" aria-label="With textarea" rows="10" cols="250" placeholder="Your message"></textarea>-->
<!--    </div>-->
<!--    <div>-->
<!--        <br><button type="submit" class="btn btn-success">Save</button>-->
<!--    </div>-->
<!--</form>-->

<?php
$title = 'Add new comment';
$this->headTitle($title);
?>

<h1><?= $this->escapeHtml($title) ?></h1>
<?php

$name = $form->get('name');
$name->setAttribute('class', 'form-control');
$name->setAttribute('placeholder', 'Username');

$email = $form->get('email');
$email->setAttribute('class', 'form-control');
$email->setAttribute('placeholder', 'Email');

$desc = $form->get('desc');
$desc->setAttribute('class', 'form-control');
$desc->setAttribute('placeholder', 'Description');

$submit = $form->get('submit');
$submit->setAttribute('class', 'btn btn-success');

$form->setAttribute('action', $this->url('blog', ['action' => 'add']));
$form->prepare();

echo $this->form()->openTag($form);
?>

<div class="form-group">
    <?= $this->formLabel($name) ?>
    <?= $this->formElement($name) ?>
    <?= $this->formElementErrors()->render($name, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($email) ?>
    <?= $this->formElement($email) ?>
    <?= $this->formElementErrors()->render($email, ['class' => 'help-block']) ?>
</div>

<div class="form-group">
    <?= $this->formLabel($desc) ?>
    <?= $this->formElement($desc) ?>
    <?= $this->formElementErrors()->render($desc, ['class' => 'help-block']) ?>
</div>

<?php

echo $this->formSubmit($submit);
echo $this->formHidden($form->get('id'));
echo $this->form()->closeTag();