


<!--<form action="/" method="post">-->
<!--    <div class="form-group">-->
<!--        <label for="exampleInputText">Username</label>-->
<!--        <input type="text" name="name" value="" class="form-control" id="exampleInputText" placeholder="Username" required/>-->
<!--    </div>-->
<!--    <div class="form-group">-->
<!--        <label for="exampleInputEmail1">Email address</label>-->
<!--        <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" required/>-->
<!--        <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>-->
<!--    </div>-->
<!--    <div class="input-group">-->
<!--        <div class="input-group-prepend">-->
<!--            <span class="input-group-text">Enter message:</span>-->
<!--        </div>-->
<!--        <textarea name="desc" class="form-control" aria-label="With textarea" rows="10" cols="250" placeholder="Your message"></textarea>-->
<!--    </div>-->
<!--    <div>-->
<!--        <br><button type="submit" class="btn btn-success">Save</button>-->
<!--    </div>-->
<!--</form>-->

<?php

    $title = 'Comments';
    $this->headTitle($title);
    ?>
    <h1><?= $this->escapeHtml($title) ?></h1>

    <table class="table">
        <tr>
            <th>Username</th>
            <th>Email</th>
            <th>Description</th>
            <th>Created</th>
            <th>Updated</th>

        </tr>
        <?php foreach ($paginator as $comment) : ?>
            <tr>

                <td><?= $this->escapeHtml($comment->name) ?></td>
                <td><?= $this->escapeHtml($comment->email) ?></td>
                <td><?= $this->escapeHtml($comment->desc) ?></td>
                <td><?= $this->escapeHtml($comment->created_at) ?></td>
                <td><?= $this->escapeHtml($comment->updated_at) ?></td>
                <td>
                    <a href="<?= $this->url('blog', ['action' => 'edit', 'id' => $comment->id]) ?>">Edit</a>
                    <a href="<?= $this->url('blog', ['action' => 'delete', 'id' => $comment->id]) ?>">Delete</a>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>

<?= $this->paginationControl(
// The paginator object:
    $this->paginator,
    // The scrolling style:
    'sliding',
    // The partial to use to render the control:
    'partial/paginator',
    // The route to link to when a user clicks a control link:
    ['route' => 'home']
) ?>


